version: "2"

run:
  modules-download-mode: 'readonly'

linters:
  enable:
    - 'asciicheck'
    - 'bodyclose'
    - 'dogsled'
    - 'errcheck'
    - 'errorlint'
    - 'copyloopvar'
    - 'goheader'
    - 'gomodguard'
    - 'goprintffuncname'
    - 'gosec'
    - 'govet'
    - 'ineffassign'
    - 'makezero'
    - 'misspell'
    - 'noctx'
    - 'paralleltest'
    - 'prealloc'
    - 'predeclared'
    - 'revive'
    - 'sqlclosecheck'
    - 'staticcheck'
    - 'unconvert'
    - 'unused'
    - 'whitespace'
  exclusions:
    paths:
      - 'assets'

formatters:
  enable:
    - 'gofumpt'
    - 'goimports'

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
