FROM postgres:{{ .Version }} AS builder

LABEL maintainer={{ .Maintainer }}

# Set non-interactive mode for apt and configure locale
ENV DEBIAN_FRONTEND=noninteractive
ENV LANG=de_DE.UTF8

RUN localedef -i de_DE -c -f UTF-8 -A /usr/share/locale/locale.alias de_DE.UTF-8 \
    {{ if .InstallTools }} && apt-get update \
    && apt-get install -y --no-install-recommends {{ .Tools }} \
    && rm -rf /var/lib/apt/lists/* {{ end }}

# Here you would use COPY for only the files you need in the image.

# Switch to non-root user (assuming 'postgres' is available, adjust as needed)
USER postgres

# Run postgres
CMD ["postgres"]
